# -*- coding: utf-8 -*-
"""
/***************************************************************************
 GeoJourney
                                 A QGIS plugin
 Ce plugin génère des routes à partir de points et créer une carte de voyage
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2026-08-15
        copyright            : (C) 2026 by Angéline Pinilo
        email                : angeline.pinilo@gmail.com
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load GeoJourney class from file GeoJourney.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .geo_journey import GeoJourney
    return GeoJourney(iface)
