# -*- coding: utf-8 -*-
"""
/***************************************************************************
 GeoJourneyDialog
                                 A QGIS plugin
 Ce plugin génère des routes à partir de points et créer une carte de voyage
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2026-08-15
        git sha              : $Format:%H$
        copyright            : (C) 2026 by Angéline Pinilo
        email                : angeline.pinilo@gmail.com
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
"""

import os

from qgis.PyQt import uic
from qgis.PyQt import QtWidgets

# This loads your .ui file so that PyQt can populate your plugin with the elements from Qt Designer
FORM_CLASS, _ = uic.loadUiType(
    os.path.join(
        os.path.dirname(__file__),
        'geo_journey_dialog_base.ui'),
    from_imports=True,
    import_from='geo_journey')


class GeoJourneyDialog(QtWidgets.QDialog, FORM_CLASS):
    def __init__(self, parent=None):
        """Constructor."""
        super(GeoJourneyDialog, self).__init__(parent)
        # Set up the user interface from Designer through FORM_CLASS.
        # After self.setupUi() you can access any designer object by doing
        # self.<objectname>, and you can use autoconnect slots - see
        # http://qt-project.org/doc/qt-4.8/designer-using-a-ui-file.html
        # #widgets-and-dialogs-with-auto-connect
        self.setupUi(self)
        self.inputmQgsFileWidget.fileChanged.connect(self.update_fields)

    def read_file(self, input_file : str) :

        if os.path.splitext(input_file)[1].lower()  == '.csv' :
            layer = QgsVectorLayer(f"file:///{input_file}?delimiter=,&detectTypes=yes", "input", "delimitedtext")
        else :
            layer = QgsVectorLayer(input_file, "input", "ogr")

        if not layer.isValid():
            print("Couche non chargée")
            return None
        else :
            return layer

    def update_fields(self, path : str ):
        layer = self.read_file(path)
        # self.load_fields(layer)

        if layer is None :
            self.stepmFieldComboBox.setLayer(None)
            self.movementmFieldComboBox.setLayer(None)
            return
        else :
            print("Couche valide :", layer.isValid())
            self.stepmFieldComboBox.setLayer(layer)
            self.movementmFieldComboBox.setLayer(layer)
            return
